-- CreateTable
CREATE TABLE "EmployeeDossier" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT,
    "company" TEXT NOT NULL DEFAULT 'FAIRUP',
    "matricule" TEXT,
    "poste" TEXT,
    "departement" TEXT,
    "manager" TEXT,
    "dateIntegration" TEXT,
    "typeContrat" TEXT,
    "statutPeriodeEssai" TEXT,
    "nom" TEXT,
    "prenom" TEXT,
    "dateNaissance" TEXT,
    "nationalite" TEXT,
    "adresseResidentielle" TEXT,
    "telephonePersonnel" TEXT,
    "emailPersonnel" TEXT,
    "emailPro" TEXT,
    "identifiantRingover" TEXT,
    "extensionLigne" TEXT,
    "outilsAttribues" TEXT NOT NULL DEFAULT '[]',
    "materielInformatique" TEXT,
    "contactUrgenceNom" TEXT,
    "contactUrgenceLien" TEXT,
    "contactUrgenceTelephone" TEXT,
    "pieces" TEXT NOT NULL DEFAULT '[]',
    "sourcePdfPath" TEXT,
    "generatedPdfPath" TEXT,
    "createdById" TEXT,
    "updatedById" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "EmployeeDossier_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "EmployeeDossier_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "EmployeeDossier_updatedById_fkey" FOREIGN KEY ("updatedById") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
